### PR TITLE
Rewrite student_search_table query

### PR DESCRIPTION
**Pull request by marxjohnson**
Details on internal WR 427905

### CODE REVIEW

**Comment by marxjohnson** [comment]
I've done as much as I can to get the CI checks passing. There's mustachelint check that's failing due to multiple partials that use {{uniqid}}, not sure what we can do about that, and a load of phpcpd errors in test files that I don't have time to look at now.

The behat test is failing on MOODLE_403_STABLE due to changes in the modal API. See #154.

**Comment by marxjohnson** [comment]
I managed to fix the remaining mustachelint issue, the duplicate IDs it was complaining about weren't actually used anywhere (they were on the spinners, which are selected by class name in the Javascript). I also disabled the phpcpd check as the remaining failures were only in tests, and [it is being removed from moodle-plugin-ci](https://moodlehq.github.io/moodle-plugin-ci/CHANGELOG.html#unreleased) in any case. We're now closer to having all the checks passing, although there's still some work to do in a future PR.

**Review by SimonThornett — APPROVED** [review]
Reviewed and approved. Resolves underlying issue.

Re-formatting for consistency and traits to replace duplicate code all good.

**Review by daledavies — APPROVED** [review]
This has been reviewed by @SimonThornett so approving.

**Pull request merged**
