### PR TITLE
Passing PHPUnit tests with MOODLE_402_STABLE

### PR DESCRIPTION
**Pull request by opitz**
running tests in external_test.php as isolated processes
replaced use of deprecated 'quiz' class with 'mod_quiz\quiz_settings' and deprecated 'quiz_attempt' with 'mod_quiz\quiz_attempt'

### CODE REVIEW

**Comment by dmitriim** [comment]
Thanks for the patch @opitz !
The plugin already got ci stuff, check https://github.com/catalyst/moodle-local_assessfreq/tree/MOODLE_400_STABLE/.github/workflows  Can you please remove .github/workflows/moodle-ci.yml from that patch and rebase?

**Comment by aspark21** [comment]
@opitz 

Looks like this can be closed as this fix has been incorporated into the new MOODLE_402_STABLE branch - https://github.com/catalyst/moodle-local_assessfreq/compare/MOODLE_400_STABLE...MOODLE_402_STABLE

**Comment by aspark21** [comment]
@golenkovm you might want to add a mention of this new branch in the readme table - https://github.com/catalyst/moodle-local_assessfreq#branches

**Comment by golenkovm** [comment]
You're absolutely right @aspark21 We'll update the readme soon.

Cheers,
Misha

**Comment by golenkovm** [comment]
Hi @aspark21 readme file has been updated :+1: 

Cheers

**Pull request closed without merging**
